// @ts-check

/**
 * El sidebar del curso se genera automáticamente a partir de la estructura
 * de carpetas de `docs/`. Los prefijos numéricos (01-, 02-, ...) definen el
 * orden y se eliminan de las URLs finales.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  cursoSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
